# Generated by Django 6.0.2 on 2026-04-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_medical_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='diet_plan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
